apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  volumes:
  - name: demo-volume
    persistentVolumeClaim:
      claimName: demo-pvc
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: demo-volume
      mountPath: /usr/share/nginx/html