apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  labels:
    app: nginx # you can use this lable to connect pod with any service
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
